### ISSUE TITLE
[INFO] Unique ID field?

### ISSUE THREAD

**Issue by xme** [LetMeR00t/TA-thehive-cortex#69] opened 2023-08-29 14:53 UTC
### Request Type
Not sure to understand how "Unique ID" is used.

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  Ubuntu
| TheHive version / git hash   |  5.2.2

### Problem Description
I created several Splunk searches that creates alerts in TheHive. In my search, I created a field unique:
`|eval unique="vt_".substr(md5(hash),1,10)`
And this field is passed to the TA via the "Unique ID field.
When alerts are created, the reference is the Splunk link to the search results. But it should be my unique ID!? 
(So I can ignore alerts of the same type)
Why do I see this Splunk URL? Am I missing something?

**Comment by LetMeR00t** [comment] 2023-08-29 16:23
Hi 
Could you share with me the alert you’ve created with how you build your field in the SPL (fell free to remove sensitive part) and the configuration you have for the custom alert action or adaptive response please

thank you

**Comment by xme** [comment] 2023-08-29 18:40
Here is my query:
```
index="xxx" 
|rename ip_addr as ip
|rename asn_country_code as country
|rename asn_abuse_email as "mail"
|eval url="https://".hostname
|eval unique="ct_".substr(md5(hostname),1,10)
|eval title="Certificate Issued for: ".hostname
|eval description="A new SSL certificate has been issued: %```%Hostname      : ".hostname."%Webpage Title : ".webpage_title."%URL           : ".url." (Be careful!)%IP            : ".ip."%ASN           : ".asn."%Country       : ".country."%```"
|rex mode=sed field=description "s/%/\n/g"
|table unique,title,hostname,url,ip,autonomous-system,mail,description
```

And my alert parameters:

Alert mode: Alert Action Mode
Unique ID Field: unique
Type: alert
Source: splunk
Title: title
Description: description
Scope: only listed fields

Tx!

**Comment by LetMeR00t** [comment] 2023-08-29 20:28
Thank you for the prompt reply.
Just to be sure about the behaviour that seems to be a confirmed bug when looking at my code, could you provide me an output example of the thehive field filled accordingly to your configuration please ?
It’ll help me to confirm the situation you’re facing 
Thank you

**Comment by xme** [comment] 2023-08-30 06:55
Here is an example of generated alert:
<img width="1958" alt="Screenshot 2023-08-30 at 08 52 58" src="https://github.com/LetMeR00t/TA-thehive-cortex/assets/480944/c6c3480d-ff23-4c22-8014-7543f817e3da">
There is the link to the SPL search instead of the generated reference!

**Comment by xme** [comment] 2023-08-31 05:04
Perfect for me! Tx!
<img width="1634" alt="Screenshot 2023-08-31 at 07 02 57" src="https://github.com/LetMeR00t/TA-thehive-cortex/assets/480944/3085e379-4946-489b-ad32-db6dd857b85f">
Exactly what I expected!

**Comment by LetMeR00t** [comment] 2023-08-31 05:12
Good to know that it’s working
It’ll be released in the next release accordingly 
Thank you

**Closed** 2023-10-28 07:29 UTC
Labels: bug, confidence_level:high
