### ISSUE TITLE
[BUG] Logging issue with the application

### ISSUE THREAD

**Issue by Krook9d** [LetMeR00t/TA-thehive-cortex#72] opened 2023-10-31 15:35 UTC
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  Ubuntu 20.04.6 LTS
| TheHive version / git hash   |  5.1.1-1

### Problem Description

Hello, I have installed the application on my company's Splunk. I have set the logs to DEBUG mode, and when I add a new instance and perform a "list case" operation and check the log, I only see the log message "DEBUG common:32 [S2] Logging mode set to DEBUG" in the logs. No other logs are present, and when I set it to something other than DEBUG, I see nothing at all.
I tried to change the access rights for the "command_thehive_search_cases.log" file, but that didn't make any difference. I don't understand why the app can write "Logging mode set to DEBUG" but not the rest of the logs. I also installed the latest version of the app, but that didn't change anything either.

### Possible Solutions
-

### Logs (issued from the search.log with logging mode set to DEBUG under Settings/Configuration)
-

**Comment by LetMeR00t** [comment] 2023-10-31 16:16
Hi @Krook9d ,
Yes, it seems weird to not have any log at all.
Could you confirm (and share with me here or by email with sensitive information removed) to have configured an account linked to your instance? Do you see your instance in the dashboard/lookup used for it ?
My guess would be to have more details about your configuration because you should have more logs when doing so.
Thank you

**Comment by LetMeR00t** [comment] 2023-11-04 07:33
Hi @Krook9d ,
Any update so far ?

**Comment by Krook9d** [comment] 2023-11-07 09:31
Sorry for the delay.

Here is my log; I only have this one:

<img width="482" alt="image" src="https://github.com/LetMeR00t/TA-thehive-cortex/assets/40600995/e3f3fee8-610a-4ede-8814-3faba3069e97">

And this log is generated every time I go into "The Hive case," click on "LIST," and select my instance.

Yes, I have an instance configured that I can see.

<img width="894" alt="image" src="https://github.com/LetMeR00t/TA-thehive-cortex/assets/40600995/e926da40-8127-45ae-abe0-d5d61c99f48d">

However, the strange thing is that I configured another development platform with a Splunk & Hive instance using the app, and in this environment, I have all the logs that I need.

So, it seems to be an issue with the working environment, but it's odd to have only one type of log instead of nothing.

What can I test to see if the app is attempting to produce logs but is being stopped by the system or something else?

**Comment by LetMeR00t** [comment] 2023-11-07 17:21
Hi 
The URI is empty which is unexpected and should be set to “/“ at least 
Could you test that please ?

**Comment by Krook9d** [comment] 2023-11-09 10:31
Yes, I apologize. This screenshot is just an example from a development environment. Unfortunately, I cannot take screenshots of my production environment, but the URI is indeed set to '/ ' in my production environnent.
I may have made a hasty judgment when I said it was a log issue. It's possible that the logs are fine, but the scripts responsible for the 'list case' and 'list alert' functions may not be triggering, which is why only the log I mentioned earlier is appearing

**Comment by LetMeR00t** [comment] 2023-11-11 13:36
Hi @Krook9d ,
No problem and it's fully understandable to not share production environment information.
My point was to say that if you configured your instance AND you enabled the DEBUG mode for the logging, you should have a lot of more logs that just only what you gave me.
If it's not the case, it means that the issue is elsewhere.
Could you maybe check the search.log file of the search running the list alert/case ? Open the search, click on the Job information and check within the logs if around the bottom of the file you have something like a bunch of errors (shown as a python stacktrace).
Let me know if it helps, otherwise we will need to find another way to help you.

**Comment by LetMeR00t** [comment] 2023-11-18 17:30
Hi @Krook9d ,
Any update on this ?

**Comment by Krook9d** [comment] 2023-11-20 14:56
I have sent you a mail

**Comment by LetMeR00t** [comment] 2023-11-20 16:52
Hello 
I didn’t received anything today for your information

**Comment by LetMeR00t** [comment] 2023-12-18 10:27
Hello @Krook9d ,
I didn't see anything about your issue in my emails, could you check again please ?

**Comment by Krook9d** [comment] 2023-12-20 09:43
> Hello @Krook9d ,
> I didn't see anything about your issue in my emails, could you check again please ?

I've send you new elements by mail

**Comment by LetMeR00t** [comment] 2024-01-04 02:33
Issue fixed by email.
Problem was coming from a BIND IP setting set up preventing calls on the Splunk API on the loopback IP

**Closed by LetMeR00t** 2024-01-04 02:33 UTC
Labels: help wanted
